# Generated by Django 3.2.4 on 2021-06-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='CartProduct',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='is_done',
            new_name='is_finalised',
        ),
    ]
