# Generated by Django 3.2.4 on 2021-06-28 18:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_auto_20210628_1945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='owner',
            new_name='customer',
        ),
    ]
